version: '3.9'

services:
  index:
    build: .
    ports:
      - '8000:8000'
  db:
    build: ./database
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data 
  frontend:
    container_name: frontend_container
    image: amralaa21/front-image
    ports:
      - '3000:3000'
volumes:
  data: